### ISSUE TITLE
Problem with ruby instaled by RBENV or RVM

### ISSUE THREAD

**Issue by jonatanrdsantos** [maximozsec/organon#1]
I usually install ruby on my system using [RBENV](https://github.com/sstephenson/rbenv) or [RVM](https://rvm.io/), then the User root does not have the ruby because RBENV/RVM install the binary in home folder like: `/home/joridos/.rvm/src/ruby`.

I think the correct way to run the installation script is not "sudo ./install.sh" but "./install.sh" script and put sudo in apt-get commands.

**Comment by mxm0z** [comment]
Thanks for the issue!

Commits d7d3e8f24e89836e42d08d59f8bfcf4aff093e7d 7bea45405bd84f59f313d12fa0632d2562b42c24 closes #1
