### ISSUE TITLE
Ferramentas que não estão presentes

### ISSUE THREAD

**Issue by Sup3r-Us3r** [maximozsec/organon#11]
**Porque tiraram ferramentas como o Beef, Setoolkit ?**

**Comment by fnk0c** [comment]
Desculpe a demora.

Quando foi trocada a estrutura dos pkgconfig acabei esquecendo deles. Tentarei adicionar em breve.
Caso queira criar os pacotes para essas e outras ferramentas, você pode seguir [esta documentação](https://github.com/fnk0c/organon-packages/blob/master/doc/README_pt.md). Existe uma ferramenta que facilita a criação dos pacotes.

Obrigado

**Comment by fnk0c** [comment]
Estarei fechando este issue e "movendo" ele para o [repositório dos pacotes](https://github.com/fnk0c/organon-packages/)
