### ISSUE TITLE
Use bundle for ruby dependencies

### ISSUE THREAD

**Issue by jonatanrdsantos** [maximozsec/organon#2]
I think if we use [bundle.io](http://bundler.io/) to manage the dependencies - gems mysql and colorize - would be good

**Comment by jonatanrdsantos** [comment]
Look, is much better:

![image ](http://i.imgur.com/OwB4F4f.png bundle result)

The makefile in ea94f57 I remove, is just an test

**Comment by mxm0z** [comment]
Thank you, man! I really had have thought about it but I had not done yet
