### ISSUE TITLE
Ferramantas para adicionar

### ISSUE THREAD

**Issue by htrgouvea** [maximozsec/organon#7]
Segue abaixo uma lista de ferramentas válidas a serem adicionadas no Organon:
- Nome: Find My Hash
- Descrição: Ferramenta de auxilo para "quebras" de hash's.
- Github: https://github.com/Talanor/findmyhash

---
- Nome: Rounter Hunter 2.0
- Descrição: Ferramenta usada para encontrar vulnerabilidades em rotiadores
- Github: https://github.com/jh00nbr/Routerhunter-2.0

---
- Nome: Virgulino
- Descrição: Ferramenta para trabalhos de esteganografia
- Github: https://github.com/lampiaosec/virgulino

---
- Nome: WiFi Pumpkin
- Descrição: Framework para testes de redes WiFi
- Github: https://github.com/P0cL4bs/WiFi-Pumpkin

---
- Nome: 0d1n
- Descrição: Ferramenta para fuzzing HTTP/HTTPS
- Github: https://github.com/CoolerVoid/0d1n

**Comment by fnk0c** [comment]
Ótima sugestão! Irei adicionar assim que possível

**Comment by fnk0c** [comment]
Adicionado FindMyHash >> https://github.com/fnk0c/organon-packages/commit/5c12a76bd7bc96d95ecb6ce6dd72e1c407ec9abb

**Comment by fnk0c** [comment]
Adicionado Virgulino >> https://github.com/fnk0c/organon-packages/commit/99fa9ac6346018416c7c0fafa0e118ac6f8a3d82

Porém ao tentar compilar, mesmo seguindo a wiki deles, ocorre um erro. Entrei em contato com um dos desenvolvedores para saber mais a respeito.

**Comment by fnk0c** [comment]
Adicionado Router Hunter >> https://github.com/fnk0c/organon-packages/commit/81da98974cfb25c69a146dc69d5e9cbd7e2543b3

**Comment by fnk0c** [comment]
Estarei fechando este issue e "movendo" ele para o [repositório dos pacotes](https://github.com/fnk0c/organon-packages/)
