### ISSUE TITLE
Não consigo instalar packages

### ISSUE THREAD

**Issue by viniciusmedeeiros** [maximozsec/organon#8]
Quando dou o comando: " Organon -i t50 " ou qualquer outro programa disponivel no repositorio, ele me retorna a seguinte mensagem:

Packages (1) t50
Traceback (most recent call last):
  File "organon.py", line 174, in <module>
    main()
  File "organon.py", line 121, in main
    core.install(args.i, args.yes)
  File "src/atom.py", line 82, in install
    choice = raw_input("\n %s[+]%s Continue the installation? [Y/n] " % \
UnboundLocalError: local variable 'raw_input' referenced before assignment

Minha distro é a Debian Jessie

**Comment by fnk0c** [comment]
Este problema é referente a versão do Python sendo utilizada. Tente executar utilizando a versão 3.x

Instale o Python 3.x
`sudo apt-get install python3`

edite o link simbólico com o vim ou outro editor de texto de sua preferência

`sudo vim /usr/bin/organon`

substitua **python organon.py $@** por **python3 organon.py $@** e salve. 
Isto deve resolver o problema

**Comment by viniciusmedeeiros** [comment]
Beleza! Chegar em casa vou tentar! Vlw

Em quarta-feira, 25 de maio de 2016, Franco Colombino <
notifications@github.com> escreveu:

**Comment by JoseCage** [comment]
Olá @fnk0c tentei aqui também e o erro persiste. Podia ajudar?

**Comment by fnk0c** [comment]
Não esqueci de vocês. É que está meio corrido pra mim. Em breve retorno com as possíveis soluções

**Comment by fnk0c** [comment]
commit https://github.com/fnk0c/organon/commit/d60aec70e6aa3cf66c78cf5811086b7012837292 deve ter solucionado o problema de vocês.

Peço que removam o cangibrina por completo e reinstalem ele.

```
git clone https://github.com/fnk0c/organon
cd organon
python3 setup.py uninstall
python3 setup.py install
```

O organon ainda não está funcional, portante algumas ferramentas, maioria nos sistemas debian, podem não funcionar. No Arch Linux grande parte ja está utilizavel.

Agradeço a vocês por estarem testando. A ferramentas que conseguirem instalar, e as que não conseguirem, favor criar um issue aqui para que eu possa resolver.

**Comment by JoseCage** [comment]
@fnk0c  Conforme sugeriu, removi e voltei a instalar o organon (até ai tudo certo), mas ao instalar o t50 retorna-me o seguinte: 

organon -i t50  
sh: 0: getcwd() failed: No such file or directory

 Packages (1) t50

 [+] Continue the installation? [Y/n] y
--2016-06-04 08:03:00--  https://projetos.cienciahacker.ch/organon/mirror/debian/i686/pkgconfig/t50.conf
Resolvendo projetos.cienciahacker.ch (projetos.cienciahacker.ch)... 46.101.211.220
Conectando-se a projetos.cienciahacker.ch (projetos.cienciahacker.ch)|46.101.211.220|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 365 [text/plain]
Salvando em: “/var/cache/organon/t50.conf”

t50.conf                        100%[=======================================================>]     365  --.-KB/s    in 0s      

2016-06-04 08:03:07 (5,25 MB/s) - “/var/cache/organon/t50.conf” salvo [365/365]

Traceback (most recent call last):
  File "organon.py", line 174, in <module>
    main()
  File "organon.py", line 121, in main
    core.install(args.i, args.yes)
  File "src/atom.py", line 109, in install
    s = install.read()
  File "src/retrieve.py", line 87, in read
    version = pkgconfig.index("version")
ValueError: 'version' is not in list

**Comment by fnk0c** [comment]
As modificações no [repositorio](https://github.com/fnk0c/organon-packages) de mirror deve ter resolvido.

Limpe o cache
`organon --clean` 

sincronize o banco de dados
`organon -S`

tente instalar o t50
`organon -i t50`

tente executa-lo
`t50 --help`

**Comment by JoseCage** [comment]
Genial @fnk0c... Agora foi... :+1: 

Valeu..

**Comment by fnk0c** [comment]
Ai sim. Vou fechar o issue então. Caso o @viniciusmedeeiros não tenha conseguido ainda eu reabro

**Comment by viniciusmedeeiros** [comment]
Tudo certo por aqui amigos, obrigado pela ajuda!

2016-06-09 20:01 GMT-03:00 Franco Colombino notifications@github.com:
