### ISSUE TITLE
erro 13

### ISSUE THREAD

**Issue by recabita** [maximozsec/organon#9]
python3 setup.py install
 [+] Creating symlink
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    install()
  File "setup.py", line 47, in install
    with open("organon", "w") as symlink:
PermissionError: [Errno 13] Permission denied: 'organon'

**Comment by fnk0c** [comment]
@recabita , obrigado por reportar.

Qual o sistema que você esta utilizando? Você possui o pacote [sudo](https://pt.wikipedia.org/wiki/Sudo) instalado? Se possui, o seu usuário esta incluso no arquivo sudoers?

**Comment by recabita** [comment]
consegui obrigado
